//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Loonie_Tunes.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Loonie_Tunes.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id,Name
        ///114013,&quot;&quot;&quot;01000010&quot;&quot;&quot;
        ///160484,&quot;&quot;&quot;Aurora Borealis&quot;&quot;&quot;
        ///169858,&quot;&quot;&quot;Bee Bee&quot;&quot; Gun&quot;
        ///67396,&quot;&quot;&quot;Carriage - Christina&quot;&quot; Precious Metal Bag&quot;
        ///67389,&quot;&quot;&quot;Carriage - Exclusive&quot;&quot; Enchanting Evening Purse&quot;
        ///67392,&quot;&quot;&quot;Carriage - Exclusive&quot;&quot; Gem Studded Clutch&quot;
        ///67393,&quot;&quot;&quot;Carriage - Going Green&quot;&quot; Herb Tote Bag&quot;
        ///67390,&quot;&quot;&quot;Carriage - Maddy&quot;&quot; High Tech Bag&quot;
        ///67395,&quot;&quot;&quot;Carriage - Meeya&quot;&quot; Leather Bag&quot;
        ///67394,&quot;&quot;&quot;Carriage - Xandera&quot;&quot; Student&apos;s Satchel&quot;
        ///67387,&quot;&quot;&quot;Carriage&quot;&quot; Signature Bag&quot;
        ///117439,&quot;&quot;&quot;Da Bruisery&quot;&quot; Hot &amp; Wroth&quot;        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AuctionItemNames {
            get {
                return ResourceManager.GetString("AuctionItemNames", resourceCulture);
            }
        }
    }
}
